In [1]:
import numpy as np

In [2]:
# 1. Create a null array of size 10 but the fifth value which is 1
a = np.zeros(10,dtype=int)
a[4] = 1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [6]:
# 2. Reverse a above created array (first element becomes last)
a[::-1]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [7]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
a = np.arange(0,9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# 4. Create a 3x3x3 array with random values
np.random.random((3,3,3))

array([[[0.39954936, 0.26467574, 0.51559244],
        [0.43644455, 0.23226578, 0.25713774],
        [0.78137971, 0.43350952, 0.67534497]],

       [[0.30573843, 0.18881224, 0.76784483],
        [0.61877996, 0.84999096, 0.29639535],
        [0.35089765, 0.42588586, 0.29609906]],

       [[0.50266083, 0.43381867, 0.98268351],
        [0.50293124, 0.90978648, 0.96021505],
        [0.4014833 , 0.0514572 , 0.54385722]]])

In [11]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values
a = np.random.random((10,10))
a
a.min(),a.max()

(0.0024973557484010422, 0.9983424165797776)

In [12]:
# 6. Create a random vector of size 30 and find the mean value
a = np.random.random(30)
a.mean()

0.5460701015432754

In [16]:
# 7. Create a 2d array with 1 on the border and 0 inside
a = np.ones(shape=(3,3),dtype=int)
a
# To make it possible we have to select middle part except borders
a[1:-1,1:-1]
# Now make it zero
a[1:-1,1:-1]=0
a

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [19]:
#7(2) Similarly for 4x4
a = np.ones(shape=(4,4),dtype=int)
a
# Middle part
a[1:-1,1:-1]
# Now make this part zero
a[1:-1,1:-1]=0
a

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [20]:
# 8. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element
a = np.empty(shape=(6,7,8),dtype=int)
a.shape
a.ndim
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [21]:
# 9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.arange(0,15).reshape(5,3)
b = np.arange(0,6).reshape(3,2)

In [22]:
a*b
# Which is not possible actually, to acheive this we do broadcasting

ValueError: operands could not be broadcast together with shapes (5,3) (3,2) 

In [23]:
# Broadcasting
a_new = a.reshape(5,3,1)
b_new = b.reshape(1,3,2)
a_new*b_new

array([[[ 0,  0],
        [ 2,  3],
        [ 8, 10]],

       [[ 0,  3],
        [ 8, 12],
        [20, 25]],

       [[ 0,  6],
        [14, 21],
        [32, 40]],

       [[ 0,  9],
        [20, 30],
        [44, 55]],

       [[ 0, 12],
        [26, 39],
        [56, 70]]])

In [24]:
# 10. Extract the integer part of a random array
num = 3.14154545
n = int(np.round(num))
n

3

In [25]:
# 11. Create a 5x5 matrix with row values ranging from 0 to 4
a = np.random.randint(0,4,size=(5,5))
a

array([[2, 3, 1, 1, 0],
       [1, 3, 1, 3, 2],
       [3, 0, 2, 3, 1],
       [3, 3, 2, 0, 1],
       [3, 0, 0, 1, 1]])

In [26]:
# 12. Create a random vector of size 10 and sort it
a = np.random.random(10)
a
a.sort()
a

array([0.1063401 , 0.24993123, 0.34456366, 0.39256892, 0.49070857,
       0.52160788, 0.71538583, 0.84750692, 0.85044562, 0.9106466 ])

In [27]:
# 13. Consider two random array A anb B, check if they are equal
A = np.random.random((3,3))
B = np.random.random((3,3))
A==B

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [30]:
# 14.Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
a = np.arange(75).reshape(5,5,3)
b = np.arange(25).reshape(5,5)
b_new = b.reshape(5,5,1)
a*b_new

array([[[   0,    0,    0],
        [   3,    4,    5],
        [  12,   14,   16],
        [  27,   30,   33],
        [  48,   52,   56]],

       [[  75,   80,   85],
        [ 108,  114,  120],
        [ 147,  154,  161],
        [ 192,  200,  208],
        [ 243,  252,  261]],

       [[ 300,  310,  320],
        [ 363,  374,  385],
        [ 432,  444,  456],
        [ 507,  520,  533],
        [ 588,  602,  616]],

       [[ 675,  690,  705],
        [ 768,  784,  800],
        [ 867,  884,  901],
        [ 972,  990, 1008],
        [1083, 1102, 1121]],

       [[1200, 1220, 1240],
        [1323, 1344, 1365],
        [1452, 1474, 1496],
        [1587, 1610, 1633],
        [1728, 1752, 1776]]])